name: Python CI

on:
  push:
    branches:
      - main

jobs:
  setup-python:
    name: Setup Python Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: pip install uv

      - name: Install Project Dependencies
        run: uv sync

      - name: Verify Python
        run: python --version

      - name: Verify uv
        run: uv --version

      - name: Verify Pytest
        run: uv run pytest --version